// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Estudo.CálculoDeConsumo.Testes.Performance.Benchmarks.TesteDePerformanceParaObtençãoDosDigitosDoValorAPartirDoCpf.ConcatESubstring~System.String")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Estudo.CálculoDeConsumo.Testes.Performance.Benchmarks.TesteDePerformanceParaObtençãoDosDigitosDoValorAPartirDoCpf.InterpolaçãoESubString~System.String")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Estudo.CálculoDeConsumo.Testes.Performance.Benchmarks.TesteDePerformanceParaObtençãoDosDigitosDoValorAPartirDoCpf.ConcatEAcessoDiretoAsPosiçõesDoCpf~System.String")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Estudo.CálculoDeConsumo.Testes.Performance.Benchmarks.TesteDePerformanceParaObtençãoDosDigitosDoValorAPartirDoCpf.InterpolaçãoEAcessoDiretoAsPosiçõesDoCpf~System.String")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Estudo.CálculoDeConsumo.Testes.Performance.Benchmarks.TesteDePerformanceParaParseDeStringDeQuatroDigitosParaInteiro.ParseDeDecimal~System.Decimal")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Estudo.CálculoDeConsumo.Testes.Performance.Benchmarks.TesteDePerformanceParaParseDeStringDeQuatroDigitosParaInteiro.ParseDeDoubleEConvertidoParaDecimal~System.Decimal")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Estudo.CálculoDeConsumo.Testes.Performance.Benchmarks.TesteDePerformanceParaParseDeStringDeQuatroDigitosParaInteiro.ParseDeInteiro~System.Int32")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Estudo.CálculoDeConsumo.Testes.Performance.Benchmarks.TesteDePerformanceParaProcessamentoDeListaDeTarefas.CriarListaDeTarefasEUsarContinueWithComLockManual~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Estudo.CálculoDeConsumo.Testes.Performance.Benchmarks.TesteDePerformanceParaProcessamentoDeListaDeTarefas.CriarSynchronizedCollectionEUsarContinueWith~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Estudo.CálculoDeConsumo.Testes.Performance.Benchmarks.TesteDePerformanceParaProcessamentoDeListaDeTarefas.CriarListaDeTarefasERemoverManualmenteAntesDeInserirNovas~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Estudo.CálculoDeConsumo.Testes.Performance.Benchmarks.TesteDePerformanceParaProcessamentoDeListaDeTarefas.CriarListaDeTarefasDoTipoStructERemoverManualmenteAntesDeInserirNovas~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2012:Use ValueTarefas correctly", Justification = "<Pending>", Scope = "member", Target = "~M:Estudo.CálculoDeConsumo.Testes.Performance.Benchmarks.TesteDePerformanceParaProcessamentoDeListaDeTarefas.CriarListaDeTarefasDoTipoStructERemoverManualmenteAntesDeInserirNovas~System.Threading.Tasks.Task")]
